# This file was generated by GoReleaser. DO NOT EDIT.
cask "lunacli" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "eec548f994a089444a27c9ccffc0ac29737025946d3298cddd8ad6dc592dcdfb"
      url "https://github.com/ba0f3/lunacli/releases/download/v#{version}/lunacli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aae645e05ea5055621a2fc7fabb18aa408b7c457815f491eaa1197a891628221"
      url "https://github.com/ba0f3/lunacli/releases/download/v#{version}/lunacli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5fcd747578485320ee200ab84ee68d25ee7126169a68f375c22597bb67b88d8b"
      url "https://github.com/ba0f3/lunacli/releases/download/v#{version}/lunacli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "81b9843eeba2fc9e9be94551af3f842d6ee5cb0d931df360b6a4f96b78d48d9c"
      url "https://github.com/ba0f3/lunacli/releases/download/v#{version}/lunacli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lunacli"
  desc "Zero-trust stdio MCP server for secure remote SSH commands"
  homepage "https://github.com/ba0f3/lunacli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "luna"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/luna"] if OS.mac?
  end

  # No zap stanza required

end
